CREATE DATABASE IF NOT EXISTS lessonplanner_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lessonplanner_db;

CREATE TABLE IF NOT EXISTS lesson_plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    teacher VARCHAR(255) NOT NULL,
    school VARCHAR(255) NOT NULL,
    grade_level VARCHAR(100) NOT NULL,
    subject VARCHAR(150) NOT NULL,
    subject_color VARCHAR(20) DEFAULT '#dbeafe',
    plan_type VARCHAR(80) NOT NULL DEFAULT 'DepEd 2026 Appendix A Lesson Plan',
    curriculum VARCHAR(255) NOT NULL,
    term VARCHAR(50) NOT NULL,
    week_day VARCHAR(100) NOT NULL,
    lesson_date DATE NULL,
    duration VARCHAR(100) NOT NULL,
    no_sessions VARCHAR(100) NULL,
    references_used TEXT NULL,
    declaration_ai_use TEXT NULL,
    topic VARCHAR(255) NOT NULL,
    content_standards TEXT NULL,
    performance_standards TEXT NULL,
    competency TEXT NOT NULL,
    objectives TEXT NOT NULL,
    learner_context TEXT NULL,
    integration TEXT NULL,
    materials TEXT NULL,
    class_profile TEXT NULL,
    pre_lesson TEXT NULL,
    lesson_flow LONGTEXT NULL,
    language_instruction VARCHAR(100) NULL,
    assessment TEXT NULL,
    remarks TEXT NULL,
    extended_learning TEXT NULL,
    reflection TEXT NULL,
    lesson_content LONGTEXT NOT NULL,
    ai_prompt LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
